### ISSUE TITLE
Deciding between PostgreSQL vs MongoDB (other options?)

### ISSUE THREAD

**Issue by dclipca** [dali-lab/wireless-tool#11]
I think it would be better to use PostgresSQL as it is relational as compared to MongoDB. I think it would save us some nerves in case we decide to gather a lot of data because Postgres is more "strong-typed" than MongoDB, although MongoDB is approximately 250% faster.

We don't want to retrieve and modify stuff very fast so I think PostgresSQL should be the choice. What do you think?

**Comment by jaismith** [comment]
Felix confirmed PostgreSQL is already used internally in ITC, so I'd second its use!
