### ISSUE TITLE
Handoff Doc

### ISSUE THREAD

**Issue by Sophie-wang22** [dali-lab/wireless-tool#35]
# Title

One to two sentence description.

## Type of Issue

- [ ] New feature
- [ ] Bug fix
- [ ] Documentation update

## Expected Behavior

- Item 1
- Item 2
- Item 3

## Current Behavior (if bug)

- Item 1
- Item 2
- Item 3

## Screenshots

Please attach any design screenshots if UI update.

**Comment by Sophie-wang22** [comment]
alendar.google.com/calendar/b/2/r?cid=ZGFsaS5kYXJ0bW91dGguZWR1X3ZoZWF1bWl0cHA2cGMzam0zMWtiMmdyMmc4QGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20

**Comment by Sophie-wang22** [comment]
calendar.google.com/calendar/b/2/r?cid=ZGFsaS5kYXJ0bW91dGguZWR1X3ZoZWF1bWl0cHA2cGMzam0zMWtiMmdyMmc4QGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20

**Comment by Sophie-wang22** [comment]
https://docs.google.com/document/d/1Rq6ur6zHEJgEph0IJjEYOXISN55Hum2PIEWNJ82YuHs/edit#

**Comment by erlobel** [comment]
@Sophie-wang22  What you have looks great! remember to add in the a section describing the decisions made this term. e.g. why did you decide one design/experience over an other? or one dev tool over the other?
